// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/sofa/sofa.proto

package upload

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UploadRequest struct {
	VideoData            []byte   `protobuf:"bytes,1,opt,name=VideoData,proto3" json:"VideoData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadRequest) Reset()         { *m = UploadRequest{} }
func (m *UploadRequest) String() string { return proto.CompactTextString(m) }
func (*UploadRequest) ProtoMessage()    {}
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca493da288556ba5, []int{0}
}

func (m *UploadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadRequest.Unmarshal(m, b)
}
func (m *UploadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadRequest.Marshal(b, m, deterministic)
}
func (m *UploadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadRequest.Merge(m, src)
}
func (m *UploadRequest) XXX_Size() int {
	return xxx_messageInfo_UploadRequest.Size(m)
}
func (m *UploadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadRequest proto.InternalMessageInfo

func (m *UploadRequest) GetVideoData() []byte {
	if m != nil {
		return m.VideoData
	}
	return nil
}

type UploadReply struct {
	UploadStatus         string   `protobuf:"bytes,1,opt,name=UploadStatus,proto3" json:"UploadStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadReply) Reset()         { *m = UploadReply{} }
func (m *UploadReply) String() string { return proto.CompactTextString(m) }
func (*UploadReply) ProtoMessage()    {}
func (*UploadReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca493da288556ba5, []int{1}
}

func (m *UploadReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadReply.Unmarshal(m, b)
}
func (m *UploadReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadReply.Marshal(b, m, deterministic)
}
func (m *UploadReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadReply.Merge(m, src)
}
func (m *UploadReply) XXX_Size() int {
	return xxx_messageInfo_UploadReply.Size(m)
}
func (m *UploadReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadReply.DiscardUnknown(m)
}

var xxx_messageInfo_UploadReply proto.InternalMessageInfo

func (m *UploadReply) GetUploadStatus() string {
	if m != nil {
		return m.UploadStatus
	}
	return ""
}

func init() {
	proto.RegisterType((*UploadRequest)(nil), "upload.UploadRequest")
	proto.RegisterType((*UploadReply)(nil), "upload.UploadReply")
}

func init() { proto.RegisterFile("proto/sofa/sofa.proto", fileDescriptor_ca493da288556ba5) }

var fileDescriptor_ca493da288556ba5 = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0xce, 0x4f, 0x4b, 0x04, 0x13, 0x7a, 0x60, 0xbe, 0x10, 0x5b, 0x69, 0x41, 0x4e,
	0x7e, 0x62, 0x8a, 0x92, 0x2e, 0x17, 0x6f, 0x28, 0x98, 0x15, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c,
	0x22, 0x24, 0xc3, 0xc5, 0x19, 0x96, 0x99, 0x92, 0x9a, 0xef, 0x92, 0x58, 0x92, 0x28, 0xc1, 0xa8,
	0xc0, 0xa8, 0xc1, 0x13, 0x84, 0x10, 0x50, 0x32, 0xe4, 0xe2, 0x86, 0x29, 0x2f, 0xc8, 0xa9, 0x14,
	0x52, 0xe2, 0xe2, 0x81, 0x70, 0x83, 0x4b, 0x12, 0x4b, 0x4a, 0x8b, 0xc1, 0xea, 0x39, 0x83, 0x50,
	0xc4, 0x8c, 0x3c, 0x61, 0x36, 0x78, 0x24, 0xe6, 0xa5, 0xe4, 0xa4, 0x16, 0x09, 0x59, 0x70, 0xb1,
	0x41, 0x04, 0x84, 0x44, 0xf5, 0x20, 0xae, 0xd0, 0x43, 0x71, 0x82, 0x94, 0x30, 0xba, 0x70, 0x41,
	0x4e, 0xa5, 0x12, 0x83, 0x06, 0x63, 0x12, 0x1b, 0xd8, 0xed, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xd4, 0x20, 0xe6, 0xaf, 0xd4, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UploadHandlerClient is the client API for UploadHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UploadHandlerClient interface {
	Upload(ctx context.Context, opts ...grpc.CallOption) (UploadHandler_UploadClient, error)
}

type uploadHandlerClient struct {
	cc *grpc.ClientConn
}

func NewUploadHandlerClient(cc *grpc.ClientConn) UploadHandlerClient {
	return &uploadHandlerClient{cc}
}

func (c *uploadHandlerClient) Upload(ctx context.Context, opts ...grpc.CallOption) (UploadHandler_UploadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_UploadHandler_serviceDesc.Streams[0], "/upload.UploadHandler/Upload", opts...)
	if err != nil {
		return nil, err
	}
	x := &uploadHandlerUploadClient{stream}
	return x, nil
}

type UploadHandler_UploadClient interface {
	Send(*UploadRequest) error
	CloseAndRecv() (*UploadReply, error)
	grpc.ClientStream
}

type uploadHandlerUploadClient struct {
	grpc.ClientStream
}

func (x *uploadHandlerUploadClient) Send(m *UploadRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *uploadHandlerUploadClient) CloseAndRecv() (*UploadReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UploadHandlerServer is the server API for UploadHandler service.
type UploadHandlerServer interface {
	Upload(UploadHandler_UploadServer) error
}

// UnimplementedUploadHandlerServer can be embedded to have forward compatible implementations.
type UnimplementedUploadHandlerServer struct {
}

func (*UnimplementedUploadHandlerServer) Upload(srv UploadHandler_UploadServer) error {
	return status.Errorf(codes.Unimplemented, "method Upload not implemented")
}

func RegisterUploadHandlerServer(s *grpc.Server, srv UploadHandlerServer) {
	s.RegisterService(&_UploadHandler_serviceDesc, srv)
}

func _UploadHandler_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UploadHandlerServer).Upload(&uploadHandlerUploadServer{stream})
}

type UploadHandler_UploadServer interface {
	SendAndClose(*UploadReply) error
	Recv() (*UploadRequest, error)
	grpc.ServerStream
}

type uploadHandlerUploadServer struct {
	grpc.ServerStream
}

func (x *uploadHandlerUploadServer) SendAndClose(m *UploadReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *uploadHandlerUploadServer) Recv() (*UploadRequest, error) {
	m := new(UploadRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _UploadHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "upload.UploadHandler",
	HandlerType: (*UploadHandlerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _UploadHandler_Upload_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/sofa/sofa.proto",
}
